name: CI/CD

on:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r api/requirements.txt

      - name: Type check (mypy)
        run: mypy ./api --explicit-package-bases --install-types --non-interactive

      - name: Lint (black + flake8)
        run: |
          black --check ./api
          flake8 ./api
