name: SCA

on:
  pull_request:

jobs:
  security-checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install tools
        run: |
          pip install -r requirements.txt
          pip install bandit detect-secrets pip-audit

      - name: Bandit
        run: bandit -r ./api

      - name: Detect secrets
        run: detect-secrets scan ./api > .secrets.baseline

      - name: Pip audit
        run: pip-audit
